[package]
name = "dobro"
version = "0.2.5"
authors = ["Daniel Rivas <ers.daniel+dev@gmail.com>"]

[dependencies]
ncurses = "5.84.0"
# ao_rs = "0.1.5"
ao_rs = { path = "../ao-rs" }
earwax = "0.1.7"
pandora = "0.1.0"
